#include "x86_64.h"

#include <cstring>
#include <iomanip>

namespace femto::codegen::x86_64 {

std::string X86_64CodeGen::generate(lir::LIRModule& mod) {
    current_module_ = &mod;
    out_ << "; Generated by femto compiler\n\n";

    // First pass: emit all functions (this populates string_data_, float_data_, float32_data_)
    out_ << "section .text\n";
    out_ << "global _start\n\n";

    emit_runtime_stubs();

    for (auto& func : mod.functions) {
        emit_function(func);
    }

    emit_entry_point();

    // Now emit data section (after functions have populated float/string data)
    out_ << "\nsection .data\n";
    for (auto& [label, value] : mod.string_data) {
        out_ << "    " << label << ": db ";
        for (std::size_t i = 0; i < value.size(); ++i) {
            if (i > 0) out_ << ", ";
            out_ << static_cast<int>(static_cast<unsigned char>(value[i]));
        }
        out_ << ", 0\n";
    }
    for (auto& [label, value] : float_data_) {
        // Emit 8-byte IEEE 754 double
        std::uint64_t bits;
        std::memcpy(&bits, &value, sizeof(bits));
        out_ << "    " << label << ": dq 0x" << std::hex << bits << std::dec << "\n";
    }
    for (auto& [label, value] : float32_data_) {
        // Emit 4-byte IEEE 754 float
        std::uint32_t bits;
        std::memcpy(&bits, &value, sizeof(bits));
        out_ << "    " << label << ": dd 0x" << std::hex << bits << std::dec << "\n";
    }
    // Negation masks for floats
    out_ << "    __neg_float32: dd 0x80000000\n";
    out_ << "    __neg_float64: dq 0x8000000000000000\n";

    return out_.str();
}

bool X86_64CodeGen::is_float_type(lir::TypePtr type) {
    if (!type) return false;
    return type->kind == femto::sema::TypeKind::Float;
}

bool X86_64CodeGen::is_float64_type(lir::TypePtr type) {
    if (!is_float_type(type)) return false;
    return std::get<femto::sema::FloatType>(type->data).bits == 64;
}

bool X86_64CodeGen::is_float32_type(lir::TypePtr type) {
    if (!is_float_type(type)) return false;
    return std::get<femto::sema::FloatType>(type->data).bits == 32;
}

std::string X86_64CodeGen::new_string_label(const std::string& value) {
    std::string label = "__str" + std::to_string(string_counter_++);
    string_data_.push_back({label, value});
    return label;
}

std::string X86_64CodeGen::get_or_create_string_label(const std::string& value) {
    auto it = string_labels_.find(value);
    if (it != string_labels_.end()) return it->second;
    std::string label = new_string_label(value);
    string_labels_[value] = label;
    return label;
}

std::string X86_64CodeGen::new_float_label(double value) {
    std::string label = "__float64_" + std::to_string(float_counter_++);
    float_data_.push_back({label, value});
    return label;
}

std::string X86_64CodeGen::new_float32_label(float value) {
    std::string label = "__float32_" + std::to_string(float_counter_++);
    float32_data_.push_back({label, value});
    return label;
}

void X86_64CodeGen::emit_runtime_stubs() {
    // std::io::print(string8 msg) -> void
    out_ << "std.io.print:\n";
    out_ << "    ; rdi = pointer to null-terminated string\n";
    out_ << "    mov rsi, rdi\n";
    out_ << "    xor rdx, rdx\n";
    out_ << ".print_strlen:\n";
    out_ << "    cmp byte [rsi + rdx], 0\n";
    out_ << "    je .print_write\n";
    out_ << "    inc rdx\n";
    out_ << "    jmp .print_strlen\n";
    out_ << ".print_write:\n";
    out_ << "    mov rax, 1\n";       // sys_write
    out_ << "    mov rdi, 1\n";       // stdout
    out_ << "    syscall\n";
    out_ << "    ret\n\n";

    // std::io::println(string8 msg) -> void
    out_ << "std.io.println:\n";
    out_ << "    call std.io.print\n";
    out_ << "    push 10\n";          // '\n'
    out_ << "    mov rax, 1\n";       // sys_write
    out_ << "    mov rdi, 1\n";       // stdout
    out_ << "    mov rsi, rsp\n";
    out_ << "    mov rdx, 1\n";
    out_ << "    syscall\n";
    out_ << "    add rsp, 8\n";
    out_ << "    ret\n\n";

    // __builtin_exit(int32 code) -> void
    out_ << "__builtin_exit:\n";
    out_ << "    mov rax, 60\n";      // sys_exit
    out_ << "    syscall\n";
    out_ << "    ret\n\n";

    // std::string8::from_int(int64 n) -> string8
    // Simple int-to-string: handles 0, positive, and negative
    out_ << "std.string8.from_int:\n";
    out_ << "    ; rdi = int64 value\n";
    out_ << "    ; Returns pointer to static buffer in rax\n";
    out_ << "    push rbx\n";
    out_ << "    mov rax, rdi\n";
    out_ << "    mov r8, 10\n";        // divisor
    out_ << "    ; Allocate 32 bytes on stack for digits\n";
    out_ << "    sub rsp, 32\n";
    out_ << "    lea rsi, [rsp + 31]\n"; // pointer to end of buffer\n";
    out_ << "    mov byte [rsi], 0\n";   // null terminator\n";
    out_ << "    ; Handle zero\n";
    out_ << "    test rax, rax\n";
    out_ << "    jnz .from_int_loop\n";
    out_ << "    dec rsi\n";
    out_ << "    mov byte [rsi], 48\n";  // '0'\n";
    out_ << "    jmp .from_int_done\n";
    out_ << ".from_int_loop:\n";
    out_ << "    test rax, rax\n";
    out_ << "    jz .from_int_done\n";
    out_ << "    cqo\n";
    out_ << "    idiv r8\n";
    out_ << "    add dl, 48\n";          // convert to ASCII\n";
    out_ << "    dec rsi\n";
    out_ << "    mov [rsi], dl\n";
    out_ << "    jmp .from_int_loop\n";
    out_ << ".from_int_done:\n";
    out_ << "    mov rax, rsi\n";        // return pointer to string\n";
    out_ << "    add rsp, 32\n";
    out_ << "    pop rbx\n";
    out_ << "    ret\n\n";

    // std::string8::from_float(float64 f) -> string8
    // Accepts float value in xmm0 (System V ABI)
    // Returns pointer to static buffer in rax
    out_ << "std.string8.from_float:\n";
    out_ << "    ; xmm0 = float64 value to convert\n";
    out_ << "    ; Returns pointer to null-terminated string in rax\n";
    out_ << "    sub rsp, 32\n";
    out_ << "    lea rdi, [rsp]\n";      // buffer pointer\n";
    out_ << "    ; TODO: proper float-to-string conversion\n";
    out_ << "    ; For now, return '0.0' placeholder\n";
    out_ << "    mov byte [rdi], 48\n";    // '0'\n";
    out_ << "    mov byte [rdi+1], 46\n";  // '.'\n";
    out_ << "    mov byte [rdi+2], 48\n";  // '0'\n";
    out_ << "    mov byte [rdi+3], 0\n";   // null terminator\n";
    out_ << "    mov rax, rdi\n";
    out_ << "    add rsp, 32\n";
    out_ << "    ret\n\n";
}

void X86_64CodeGen::emit_entry_point() {
    out_ << "_start:\n";
    out_ << "    mov rbp, rsp\n";
    out_ << "    pop rdi\n";           // argc
    out_ << "    mov rsi, rsp\n";      // argv
    out_ << "    and rsp, -16\n";      // align stack to 16 bytes
    out_ << "    call main\n";
    out_ << "    mov rdi, rax\n";      // exit code = return value of main
    out_ << "    mov rax, 60\n";       // sys_exit
    out_ << "    syscall\n\n";
}

std::string X86_64CodeGen::reg_name(lir::VirtualReg reg) {
    auto it = reg_map_.find(reg.id);
    if (it != reg_map_.end()) return it->second;

    std::string name = "[rbp - " + std::to_string(stack_offset_ + 8) + "]";
    stack_offset_ += 8;
    reg_map_[reg.id] = name;
    return name;
}

std::string X86_64CodeGen::xmm_name(lir::VirtualReg reg) {
    auto it = xmm_map_.find(reg.id);
    if (it != xmm_map_.end()) return it->second;

    // Spill to stack - use red zone or stack slots
    xmm_stack_offset_ += 8;
    std::string name = "[rbp - " + std::to_string(stack_offset_ + xmm_stack_offset_) + "]";
    xmm_map_[reg.id] = name;
    return name;
}

void X86_64CodeGen::emit_function(lir::LIRFunction& func) {
    reg_map_.clear();
    xmm_map_.clear();
    var_map_.clear();
    stack_offset_ = 0;
    xmm_stack_offset_ = 0;

    out_ << func.name << ":\n";
    emit_prologue(func);

    for (auto& block : func.blocks) {
        if (!block.label.empty()) {
            out_ << block.label << ":\n";
        }
        bool block_terminated = false;
        for (auto& inst : block.instructions) {
            if (block_terminated) {
                // Skip instructions after Ret (dead code)
                if (inst.opcode == lir::LIROpcode::Label) {
                    block_terminated = false;
                } else {
                    continue;
                }
            }
            emit_instruction(inst, func);
            if (inst.opcode == lir::LIROpcode::Ret) {
                block_terminated = true;
            }
        }
    }

    emit_epilogue(func);
    out_ << "\n";
}

void X86_64CodeGen::emit_prologue(lir::LIRFunction& func) {
    // Push callee-saved registers FIRST so they're above rbp
    for (auto& reg : callee_saved_) {
        out_ << "    push " << reg << "\n";
    }
    out_ << "    push rbp\n";
    out_ << "    mov rbp, rsp\n";

    // Allocate stack space for locals (int + float)
    int local_count = static_cast<int>(func.params.size()) + 32;
    int alloc = (local_count * 8 + 15) & ~15;
    if (alloc > 0) {
        out_ << "    sub rsp, " << alloc << "\n";
    }

    // Save integer parameters from registers to stack slots
    int int_param_count = 0;
    int float_param_count = 0;
    for (std::size_t i = 0; i < func.params.size(); ++i) {
        lir::TypePtr param_type = func.params[i].second;
        std::string param_name = func.params[i].first;
        lir::VirtualReg param_reg{static_cast<lir::RegId>(i), param_type};

        if (is_float_type(param_type)) {
            // Float parameters come in xmm0-xmm7
            if (float_param_count < 8) {
                std::string suffix = is_float64_type(param_type) ? "sd" : "ss";
                std::string dest = xmm_name(param_reg);
                out_ << "    mov" << suffix << " " << dest << ", " << xmm_param_regs_[float_param_count] << "\n";
                var_map_[param_name] = {dest, param_type};
            }
            float_param_count++;
        } else {
            // Integer parameters come in rdi, rsi, rdx, rcx, r8, r9
            if (int_param_count < 6) {
                std::string dest = reg_name(param_reg);
                out_ << "    mov " << dest << ", " << param_regs_[int_param_count] << "\n";
                var_map_[param_name] = {dest, param_type};
            }
            int_param_count++;
        }
    }
}

void X86_64CodeGen::emit_epilogue(lir::LIRFunction& /*func*/) {
    out_ << "    mov rsp, rbp\n";
    out_ << "    pop rbp\n";
    for (int i = static_cast<int>(callee_saved_.size()) - 1; i >= 0; --i) {
        out_ << "    pop " << callee_saved_[i] << "\n";
    }
    out_ << "    ret\n";
}

void X86_64CodeGen::emit_instruction(lir::LIRInstruction& inst, lir::LIRFunction& func) {
    bool dest_is_float = is_float_type(inst.dest.type) || xmm_map_.count(inst.dest.id) > 0;
    bool src1_is_float = is_float_type(inst.src1.type) || xmm_map_.count(inst.src1.id) > 0;

    // Helper: determine float suffix from available type info
    auto float_suffix = [&]() -> std::string {
        if (is_float64_type(inst.type) || is_float64_type(inst.dest.type) || is_float64_type(inst.src1.type)) return "sd";
        if (is_float32_type(inst.type) || is_float32_type(inst.dest.type) || is_float32_type(inst.src1.type)) return "ss";
        // Check xmm_map_ for registered float slots
        if (xmm_map_.count(inst.dest.id) > 0 || xmm_map_.count(inst.src1.id) > 0) return "sd";
        return "sd"; // default to double
    };

    switch (inst.opcode) {
        case lir::LIROpcode::Move:
            if (inst.has_float_imm) {
                // Float immediate load
                std::string label;
                if (is_float64_type(inst.type)) {
                    label = new_float_label(inst.float_imm);
                } else {
                    label = new_float32_label(static_cast<float>(inst.float_imm));
                }
                std::string suffix = float_suffix();
                std::string dest_slot = xmm_name(inst.dest);
                // Load through xmm0 to avoid memory-to-memory move
                out_ << "    mov" << suffix << " xmm0, [" << label << "]\n";
                out_ << "    mov" << suffix << " " << dest_slot << ", xmm0\n";
                if (!inst.var_name.empty()) {
                    var_map_[inst.var_name] = {dest_slot, inst.type};
                }
            } else if (!inst.label.empty()) {
                out_ << "    lea rax, [" << inst.label << "]\n";
                out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            } else if (inst.has_imm) {
                std::string dest_slot = reg_name(inst.dest);
                out_ << "    mov " << dest_slot << ", " << inst.imm << "\n";
                if (!inst.var_name.empty()) {
                    var_map_[inst.var_name] = {dest_slot, inst.type};
                }
            } else if (dest_is_float && src1_is_float) {
                std::string suffix = float_suffix();
                std::string dest_slot = xmm_name(inst.dest);
                std::string src_slot = xmm_name(inst.src1);
                // Route through xmm0 if both are memory operands
                if (dest_slot[0] == '[' && src_slot[0] == '[') {
                    out_ << "    mov" << suffix << " xmm0, " << src_slot << "\n";
                    out_ << "    mov" << suffix << " " << dest_slot << ", xmm0\n";
                } else {
                    out_ << "    mov" << suffix << " " << dest_slot << ", " << src_slot << "\n";
                }
                if (!inst.var_name.empty()) {
                    var_map_[inst.var_name] = {dest_slot, inst.type};
                }
            } else if (dest_is_float && !src1_is_float) {
                // Int to float conversion
                std::string suffix = float_suffix();
                std::string dest_slot = xmm_name(inst.dest);
                out_ << "    cvtsi2" << suffix[0] << " " << dest_slot << ", " << reg_name(inst.src1) << "\n";
                if (!inst.var_name.empty()) {
                    var_map_[inst.var_name] = {dest_slot, inst.type};
                }
            } else if (!dest_is_float && src1_is_float) {
                // Float to int conversion
                std::string suffix = float_suffix();
                std::string dest_slot = reg_name(inst.dest);
                // Route through xmm0 if dest is also a memory operand
                std::string src_slot = xmm_name(inst.src1);
                if (dest_slot[0] == '[') {
                    out_ << "    cvtt" << suffix << "2si rax, " << src_slot << "\n";
                    out_ << "    mov " << dest_slot << ", rax\n";
                } else {
                    out_ << "    cvtt" << suffix << "2si " << dest_slot << ", " << src_slot << "\n";
                }
                if (!inst.var_name.empty()) {
                    var_map_[inst.var_name] = {dest_slot, inst.type};
                }
            } else {
                std::string dest_slot = reg_name(inst.dest);
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                out_ << "    mov " << dest_slot << ", rax\n";
                if (!inst.var_name.empty()) {
                    var_map_[inst.var_name] = {dest_slot, inst.type};
                }
            }
            break;

        case lir::LIROpcode::Load:
            if (!inst.label.empty()) {
                // Check if this is a variable name or a data label
                auto var_it = var_map_.find(inst.label);
                if (var_it != var_map_.end()) {
                    // Variable reference - use the variable's stored type for float detection
                    bool var_is_float = is_float_type(var_it->second.second);
                    if (var_is_float) {
                        std::string suffix = is_float64_type(var_it->second.second) ? "sd" : "ss";
                        std::string dest_slot = xmm_name(inst.dest);
                        std::string src_slot = var_it->second.first;
                        if (dest_slot[0] == '[' && src_slot[0] == '[') {
                            out_ << "    mov" << suffix << " xmm0, " << src_slot << "\n";
                            out_ << "    mov" << suffix << " " << dest_slot << ", xmm0\n";
                        } else {
                            out_ << "    mov" << suffix << " " << dest_slot << ", " << src_slot << "\n";
                        }
                    } else {
                        std::string dest_slot = reg_name(inst.dest);
                        // Route through rax if dest is also a memory operand
                        if (dest_slot[0] == '[') {
                            out_ << "    mov rax, " << var_it->second.first << "\n";
                            out_ << "    mov " << dest_slot << ", rax\n";
                        } else {
                            out_ << "    mov " << dest_slot << ", " << var_it->second.first << "\n";
                        }
                    }
                } else {
                    // Data label (string literal address)
                    out_ << "    lea rax, [" << inst.label << "]\n";
                    out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
                }
            } else if (inst.src2.id != 0) {
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                out_ << "    add rax, " << reg_name(inst.src2) << "\n";
                if (dest_is_float || src1_is_float) {
                    std::string suffix = float_suffix();
                    out_ << "    mov" << suffix << " " << xmm_name(inst.dest) << ", [rax]\n";
                } else {
                    out_ << "    mov " << reg_name(inst.dest) << ", [rax]\n";
                }
            } else {
                if (dest_is_float) {
                    std::string suffix = float_suffix();
                    out_ << "    mov" << suffix << " " << xmm_name(inst.dest) << ", " << reg_name(inst.src1) << "\n";
                } else {
                    out_ << "    mov " << reg_name(inst.dest) << ", " << reg_name(inst.src1) << "\n";
                }
            }
            break;

        case lir::LIROpcode::Store:
            if (src1_is_float) {
                std::string suffix = float_suffix();
                std::string dest = reg_name(inst.src1);
                std::string src = xmm_name(inst.src2);
                if (dest[0] == '[' && src[0] == '[') {
                    out_ << "    mov" << suffix << " xmm0, " << src << "\n";
                    out_ << "    mov" << suffix << " " << dest << ", xmm0\n";
                } else {
                    out_ << "    mov" << suffix << " " << dest << ", " << src << "\n";
                }
            } else {
                std::string dest = reg_name(inst.src1);
                std::string src = reg_name(inst.src2);
                out_ << "    mov rax, " << src << "\n";
                out_ << "    mov " << dest << ", rax\n";
            }
            break;

        case lir::LIROpcode::Add:
            if (dest_is_float || src1_is_float) {
                std::string suffix = float_suffix();
                std::string dest_slot = xmm_name(inst.dest);
                std::string src1_slot = xmm_name(inst.src1);
                std::string src2_slot = xmm_name(inst.src2);
                if (dest_slot[0] == '[' && src1_slot[0] == '[') {
                    out_ << "    mov" << suffix << " xmm0, " << src1_slot << "\n";
                    out_ << "    add" << suffix << " xmm0, " << src2_slot << "\n";
                    out_ << "    mov" << suffix << " " << dest_slot << ", xmm0\n";
                } else {
                    out_ << "    mov" << suffix << " " << dest_slot << ", " << src1_slot << "\n";
                    out_ << "    add" << suffix << " " << dest_slot << ", " << src2_slot << "\n";
                }
            } else {
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                out_ << "    add rax, " << reg_name(inst.src2) << "\n";
                out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            }
            break;

        case lir::LIROpcode::Sub:
            if (dest_is_float || src1_is_float) {
                std::string suffix = float_suffix();
                std::string dest_slot = xmm_name(inst.dest);
                std::string src1_slot = xmm_name(inst.src1);
                if (inst.src2.id == 0) {
                    // Unary negate for float
                    out_ << "    mov" << suffix << " " << dest_slot << ", " << src1_slot << "\n";
                    if (is_float64_type(inst.type)) {
                        out_ << "    xorpd " << dest_slot << ", [__neg_float64]\n";
                    } else {
                        out_ << "    xorps " << dest_slot << ", [__neg_float32]\n";
                    }
                } else {
                    std::string src2_slot = xmm_name(inst.src2);
                    if (dest_slot[0] == '[' && src1_slot[0] == '[') {
                        out_ << "    mov" << suffix << " xmm0, " << src1_slot << "\n";
                        out_ << "    sub" << suffix << " xmm0, " << src2_slot << "\n";
                        out_ << "    mov" << suffix << " " << dest_slot << ", xmm0\n";
                    } else {
                        out_ << "    mov" << suffix << " " << dest_slot << ", " << src1_slot << "\n";
                        out_ << "    sub" << suffix << " " << dest_slot << ", " << src2_slot << "\n";
                    }
                }
            } else {
                if (inst.src2.id == 0) {
                    out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                    out_ << "    neg rax\n";
                    out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
                } else {
                    out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                    out_ << "    sub rax, " << reg_name(inst.src2) << "\n";
                    out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
                }
            }
            break;

        case lir::LIROpcode::Mul:
            if (dest_is_float || src1_is_float) {
                std::string suffix = float_suffix();
                std::string dest_slot = xmm_name(inst.dest);
                std::string src1_slot = xmm_name(inst.src1);
                std::string src2_slot = xmm_name(inst.src2);
                if (dest_slot[0] == '[' && src1_slot[0] == '[') {
                    out_ << "    mov" << suffix << " xmm0, " << src1_slot << "\n";
                    out_ << "    mul" << suffix << " xmm0, " << src2_slot << "\n";
                    out_ << "    mov" << suffix << " " << dest_slot << ", xmm0\n";
                } else {
                    out_ << "    mov" << suffix << " " << dest_slot << ", " << src1_slot << "\n";
                    out_ << "    mul" << suffix << " " << dest_slot << ", " << src2_slot << "\n";
                }
            } else {
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                out_ << "    imul rax, " << reg_name(inst.src2) << "\n";
                out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            }
            break;

        case lir::LIROpcode::Div:
            if (dest_is_float || src1_is_float) {
                std::string suffix = float_suffix();
                std::string dest_slot = xmm_name(inst.dest);
                std::string src1_slot = xmm_name(inst.src1);
                std::string src2_slot = xmm_name(inst.src2);
                if (dest_slot[0] == '[' && src1_slot[0] == '[') {
                    out_ << "    mov" << suffix << " xmm0, " << src1_slot << "\n";
                    out_ << "    div" << suffix << " xmm0, " << src2_slot << "\n";
                    out_ << "    mov" << suffix << " " << dest_slot << ", xmm0\n";
                } else {
                    out_ << "    mov" << suffix << " " << dest_slot << ", " << src1_slot << "\n";
                    out_ << "    div" << suffix << " " << dest_slot << ", " << src2_slot << "\n";
                }
            } else {
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                out_ << "    cqo\n";
                out_ << "    idiv " << reg_name(inst.src2) << "\n";
                out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            }
            break;

        case lir::LIROpcode::Mod:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    cqo\n";
            out_ << "    idiv " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rdx\n";
            break;

        case lir::LIROpcode::And:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    and rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Or:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    or rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Xor:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    xor rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Not:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    not rax\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Shl:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    shl rax, cl\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Shr:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    shr rax, cl\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::CmpEq:
        case lir::LIROpcode::CmpNe:
        case lir::LIROpcode::CmpLt:
        case lir::LIROpcode::CmpGt:
        case lir::LIROpcode::CmpLe:
        case lir::LIROpcode::CmpGe:
            if (src1_is_float) {
                // Float comparison using ucomis
                std::string suffix = float_suffix();
                if (suffix == "ss" && is_float64_type(inst.src1.type)) suffix = "sd";
                if (suffix == "ss" && is_float64_type(inst.src2.type)) suffix = "sd";
                std::string src1_slot = xmm_name(inst.src1);
                std::string src2_slot = xmm_name(inst.src2);
                if (src1_slot[0] == '[' && src2_slot[0] == '[') {
                    out_ << "    movsd xmm0, " << src1_slot << "\n";
                    out_ << "    ucomisd xmm0, " << src2_slot << "\n";
                } else {
                    out_ << "    ucomisd " << src1_slot << ", " << src2_slot << "\n";
                }
                out_ << "    set" << (inst.opcode == lir::LIROpcode::CmpEq ? "e" :
                                      inst.opcode == lir::LIROpcode::CmpNe ? "ne" :
                                      inst.opcode == lir::LIROpcode::CmpLt ? "b" :
                                      inst.opcode == lir::LIROpcode::CmpGt ? "a" :
                                      inst.opcode == lir::LIROpcode::CmpLe ? "be" : "ae") << " al\n";
                out_ << "    movzx rax, al\n";
                out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            } else {
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                out_ << "    cmp rax, " << reg_name(inst.src2) << "\n";
                {
                    std::string set_instr;
                    switch (inst.opcode) {
                        case lir::LIROpcode::CmpEq: set_instr = "sete"; break;
                        case lir::LIROpcode::CmpNe: set_instr = "setne"; break;
                        case lir::LIROpcode::CmpLt: set_instr = "setl"; break;
                        case lir::LIROpcode::CmpGt: set_instr = "setg"; break;
                        case lir::LIROpcode::CmpLe: set_instr = "setle"; break;
                        case lir::LIROpcode::CmpGe: set_instr = "setge"; break;
                        default: set_instr = "sete"; break;
                    }
                    out_ << "    " << set_instr << " al\n";
                    out_ << "    movzx rax, al\n";
                    out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
                }
            }
            break;

        case lir::LIROpcode::LogicAnd:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    test rax, rax\n";
            out_ << "    setnz al\n";
            out_ << "    movzx rax, al\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            out_ << "    mov rax, " << reg_name(inst.src2) << "\n";
            out_ << "    test rax, rax\n";
            out_ << "    setnz al\n";
            out_ << "    movzx rax, al\n";
            out_ << "    and " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::LogicOr:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    test rax, rax\n";
            out_ << "    setnz al\n";
            out_ << "    movzx rax, al\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            out_ << "    mov rax, " << reg_name(inst.src2) << "\n";
            out_ << "    test rax, rax\n";
            out_ << "    setnz al\n";
            out_ << "    movzx rax, al\n";
            out_ << "    or " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::LogicNot:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    test rax, rax\n";
            out_ << "    setz al\n";
            out_ << "    movzx rax, al\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Jump:
            out_ << "    jmp " << inst.label << "\n";
            break;

        case lir::LIROpcode::Branch:
            if (is_float_type(inst.src1.type)) {
                // Float branch: compare with zero
                std::string suffix = float_suffix();
                out_ << "    pxor xmm7, xmm7\n";
                out_ << "    ucomis" << suffix << " " << xmm_name(inst.src1) << ", xmm7\n";
                out_ << "    jnz " << inst.label << "\n";
            } else {
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                out_ << "    test rax, rax\n";
                out_ << "    jnz " << inst.label << "\n";
            }
            break;

        case lir::LIROpcode::Call: {
            // Load arguments into parameter registers
            int int_arg_count = 0;
            int float_arg_count = 0;

            // Look up the callee's function signature to determine param types
            const lir::LIRFunction* callee_func = nullptr;
            if (current_module_) {
                for (auto& f : current_module_->functions) {
                    if (f.name == inst.label) {
                        callee_func = &f;
                        break;
                    }
                }
            }

            // First pass: count arguments and their types
            std::vector<std::pair<lir::VirtualReg, bool>> arg_info; // reg, is_float
            for (std::size_t i = 0; i < 8; ++i) {
                lir::VirtualReg arg_reg{inst.src1.id + static_cast<lir::RegId>(i), nullptr};
                auto it = reg_map_.find(arg_reg.id);
                auto xmm_it = xmm_map_.find(arg_reg.id);
                if (it != reg_map_.end() || xmm_it != xmm_map_.end()) {
                    // Determine if this arg is float from the callee's param types
                    bool is_float = false;
                    if (callee_func && i < callee_func->params.size()) {
                        is_float = is_float_type(callee_func->params[i].second);
                    }
                    arg_info.push_back({arg_reg, is_float});
                } else {
                    break;
                }
            }

            // Second pass: emit moves
            for (auto& [arg_reg, is_float] : arg_info) {
                if (is_float) {
                    if (float_arg_count < 8) {
                        std::string suffix = "sd"; // default to double
                        out_ << "    movsd " << xmm_param_regs_[float_arg_count] << ", " << xmm_name(arg_reg) << "\n";
                    }
                    float_arg_count++;
                } else {
                    if (int_arg_count < 6) {
                        out_ << "    mov " << param_regs_[int_arg_count] << ", " << reg_name(arg_reg) << "\n";
                    }
                    int_arg_count++;
                }
            }

            out_ << "    call " << inst.label << "\n";
            if (inst.dest.id != 0) {
                bool returns_float = dest_is_float || is_float_type(inst.type);
                if (!returns_float && callee_func) {
                    returns_float = is_float_type(callee_func->return_type);
                }
                if (returns_float) {
                    std::string suffix = float_suffix();
                    out_ << "    mov" << suffix << " " << xmm_name(inst.dest) << ", xmm0\n";
                } else {
                    // Check xmm_map_ as fallback - if dest was previously used as float
                    if (xmm_map_.count(inst.dest.id) > 0) {
                        out_ << "    movsd " << xmm_name(inst.dest) << ", xmm0\n";
                    } else {
                        out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
                    }
                }
            }
            break;
        }

        case lir::LIROpcode::Ret:
            if (inst.src1.id != 0) {
                if (src1_is_float) {
                    std::string suffix = float_suffix();
                    out_ << "    mov" << suffix << " xmm0, " << xmm_name(inst.src1) << "\n";
                } else {
                    out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
                }
            }
            // Epilogue: restore callee-saved regs and return
            out_ << "    mov rsp, rbp\n";
            out_ << "    pop rbp\n";
            for (int i = static_cast<int>(callee_saved_.size()) - 1; i >= 0; --i) {
                out_ << "    pop " << callee_saved_[i] << "\n";
            }
            out_ << "    ret\n";
            break;

        case lir::LIROpcode::Label:
            out_ << inst.label << ":\n";
            break;

        case lir::LIROpcode::Nop:
            out_ << "    nop\n";
            break;

        default:
            out_ << "    ; unimplemented opcode\n";
            break;
    }
}

} // namespace femto::codegen::x86_64

// DEBUG: trace callee lookup
#include <cstdio>
