#include "x86_64.h"

#include <iomanip>

namespace femto::codegen::x86_64 {

std::string X86_64CodeGen::generate(lir::LIRModule& mod) {
    out_ << "; Generated by femto compiler\n";
    out_ << "section .data\n";
    emit_data_section(mod);

    out_ << "\nsection .text\n";
    out_ << "global _start\n\n";

    for (auto& func : mod.functions) {
        emit_function(func);
    }

    // Entry point
    out_ << "_start:\n";
    out_ << "    call main\n";
    out_ << "    mov rdi, rax\n";
    out_ << "    mov rax, 60\n";
    out_ << "    syscall\n\n";

    return out_.str();
}

void X86_64CodeGen::emit_data_section(lir::LIRModule& mod) {
    // String literals would be emitted here in a full implementation
}

std::string X86_64CodeGen::new_string_label(const std::string& value) {
    auto label = ".str" + std::to_string(string_counter_++);
    string_labels_[value] = label;
    return label;
}

std::string X86_64CodeGen::reg_name(lir::VirtualReg reg) {
    auto it = reg_map_.find(reg.id);
    if (it != reg_map_.end()) return it->second;

    // Simple stack-based allocation for non-parameter registers
    std::string name = "[rbp - " + std::to_string(stack_offset_) + "]";
    stack_offset_ += 8;
    reg_map_[reg.id] = name;
    return name;
}

void X86_64CodeGen::emit_function(lir::LIRFunction& func) {
    reg_map_.clear();
    stack_offset_ = 0;

    out_ << func.name << ":\n";
    emit_prologue(func);

    for (auto& block : func.blocks) {
        if (!block.label.empty()) {
            out_ << block.label << ":\n";
        }
        for (auto& inst : block.instructions) {
            emit_instruction(inst, func);
        }
    }

    emit_epilogue(func);
    out_ << "\n";
}

void X86_64CodeGen::emit_prologue(lir::LIRFunction& func) {
    out_ << "    push rbp\n";
    out_ << "    mov rbp, rsp\n";

    // Save callee-saved registers
    for (auto& reg : callee_saved_) {
        out_ << "    push " << reg << "\n";
    }

    // Allocate stack for local variables
    out_ << "    sub rsp, 64\n";

    // Load parameters into their virtual registers
    for (std::size_t i = 0; i < func.params.size() && i < param_regs_.size(); ++i) {
        lir::VirtualReg param_reg{static_cast<lir::RegId>(i), func.params[i].second};
        std::string dest = reg_name(param_reg);
        out_ << "    mov " << dest << ", " << param_regs_[i] << "\n";
    }
}

void X86_64CodeGen::emit_epilogue(lir::LIRFunction& func) {
    out_ << "    mov rsp, rbp\n";
    out_ << "    pop rbp\n";
    for (int i = static_cast<int>(callee_saved_.size()) - 1; i >= 0; --i) {
        out_ << "    pop " << callee_saved_[i] << "\n";
    }
    out_ << "    ret\n";
}

void X86_64CodeGen::emit_instruction(lir::LIRInstruction& inst, lir::LIRFunction& func) {
    switch (inst.opcode) {
        case lir::LIROpcode::Move:
            out_ << "    mov " << reg_name(inst.dest) << ", " << reg_name(inst.src1) << "\n";
            break;

        case lir::LIROpcode::Add:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    add rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Sub:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    sub rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Mul:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    imul rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Div:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    cqo\n";
            out_ << "    idiv " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Mod:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    cqo\n";
            out_ << "    idiv " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rdx\n";
            break;

        case lir::LIROpcode::And:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    and rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Or:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    or rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Xor:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    xor rax, " << reg_name(inst.src2) << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Not:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    not rax\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Shl:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    shl rax, cl\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Shr:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    shr rax, cl\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::CmpEq:
        case lir::LIROpcode::CmpNe:
        case lir::LIROpcode::CmpLt:
        case lir::LIROpcode::CmpGt:
        case lir::LIROpcode::CmpLe:
        case lir::LIROpcode::CmpGe:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    cmp rax, " << reg_name(inst.src2) << "\n";
            {
                std::string set_instr;
                switch (inst.opcode) {
                    case lir::LIROpcode::CmpEq: set_instr = "sete"; break;
                    case lir::LIROpcode::CmpNe: set_instr = "setne"; break;
                    case lir::LIROpcode::CmpLt: set_instr = "setl"; break;
                    case lir::LIROpcode::CmpGt: set_instr = "setg"; break;
                    case lir::LIROpcode::CmpLe: set_instr = "setle"; break;
                    case lir::LIROpcode::CmpGe: set_instr = "setge"; break;
                    default: set_instr = "sete"; break;
                }
                out_ << "    " << set_instr << " al\n";
                out_ << "    movzx rax, al\n";
                out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            }
            break;

        case lir::LIROpcode::Jump:
            out_ << "    jmp " << inst.label << "\n";
            break;

        case lir::LIROpcode::Branch:
            out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            out_ << "    test rax, rax\n";
            out_ << "    jnz " << inst.label << "\n";
            break;

        case lir::LIROpcode::Call:
            // Simple: move args to param registers
            for (std::size_t i = 0; i < func.params.size() && i < 6; ++i) {
                lir::VirtualReg arg_reg{inst.src1.id + static_cast<lir::RegId>(i), nullptr};
                out_ << "    mov " << param_regs_[i] << ", " << reg_name(arg_reg) << "\n";
            }
            out_ << "    call " << inst.label << "\n";
            out_ << "    mov " << reg_name(inst.dest) << ", rax\n";
            break;

        case lir::LIROpcode::Ret:
            if (inst.src1.id != 0) {
                out_ << "    mov rax, " << reg_name(inst.src1) << "\n";
            }
            out_ << "    leave\n";
            out_ << "    ret\n";
            break;

        case lir::LIROpcode::Label:
            out_ << inst.label << ":\n";
            break;

        case lir::LIROpcode::Nop:
            out_ << "    nop\n";
            break;

        default:
            out_ << "    ; unimplemented opcode\n";
            break;
    }
}

} // namespace femto::codegen::x86_64
